set(version "")
set(result1 -1)
set(result2 -1)
set(result3 -1)
set(result4 -1)
execute_process(COMMAND git rev-parse --verify -q jq-1.0 OUTPUT_QUIET RESULT_VARIABLE result1)
if(result1 EQUAL 0)
	execute_process(COMMAND git describe --tags --dirty --match "jq-*" OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result2 OUTPUT_VARIABLE tag1)
endif()
if(result2 EQUAL 0)
	string(REGEX REPLACE "^jq-" "" version "${tag1}")
else()
	execute_process(COMMAND git rev-parse --abbrev-ref HEAD OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result3 OUTPUT_VARIABLE tag2)
	execute_process(COMMAND git describe --always --dirty OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result4 OUTPUT_VARIABLE tag3)
	set(version "${tag2}-${tag3}")
endif()

file(WRITE "${FILE}" "#define JQ_VERSION \"${version}\"\n")